# Generated by Django 4.1 on 2022-08-27 09:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField>@ecologicalpartyofuganda.com', max_length=254, unique=True)),
                ('role', models.CharField(default='Member', max_length=250)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/members/')),
                ('facebook', models.URLField(default='https://www.ecologicalpartyofuganda.com')),
                ('twitter', models.URLField(default='https://www.ecologicalpartyofuganda.com')),
                ('instagram', models.URLField(default='https://www.ecologicalpartyofuganda.com')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('category', models.CharField(default='', max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/<django.db.models.fields.CharField>')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.URLField(default='https://www.ecologicalpartyofuganda.com')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='main.member')),
            ],
            options={
                'ordering': ('created_at',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
