# Generated by Django 4.1 on 2022-08-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_candidate_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.URLField(default='https://www.ecologicalpartyofuganda.com'),
        ),
    ]
