# Generated by Django 4.1 on 2022-08-27 22:05

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blog_authored_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='source_name',
            field=models.CharField(default='EPU', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='source',
            field=models.URLField(default=main.models.get_absolute_url_default),
        ),
    ]
